### ISSUE TITLE
Some Cutting Board (Farmer's Delight) recipe crashes the game

### ISSUE THREAD

**Issue by JowMK** [kyber-6/fantasy-mc-fabric-modpack#76]
### Describe the bug

Game crashes when trying to show some cutting board recipe(s?) (at least with the straw recipe)

### Reproduction Steps

The 2 ways i got it were:
- Search bookshelf in REI
- show bookshelf recipe
- show book recipe
- show canvas recipe
- show straw recipe
- click cutting board tab
- crash
---
- search cutting board in REI
- show all cutting board recipes
- advance in the recipes tab
- crash

### Logs & crash-reports

Log report from the minecraft launcher console

15:09:40.703
net.minecraft.class_310
Render thread
Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:123)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.AbstractMethodError: Receiver class com.nhoryzon.mc.farmersdelight.integration.rei.ChanceArrayIngredient does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getSetting(me.shedaniel.rei.api.common.entry.settings.EntryIngredientSetting)' of interface me.shedaniel.rei.api.common.entry.EntryIngredient.
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.hashFocusIngredient(AbstractDisplayViewingScreen.java:282)
	at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:515)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:573)
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.unifyIngredients(AbstractDisplayViewingScreen.java:328)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.initDisplays(DefaultDisplayViewingScreen.java:253)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25426(DefaultDisplayViewingScreen.java:218)
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.selectCategory(AbstractDisplayViewingScreen.java:120)
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.selectCategory(AbstractDisplayViewingScreen.java:105)
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen$2.accept(AbstractDisplayViewingScreen.java:143)
	at me.shedaniel.rei.impl.client.gui.widget.TabContainerWidget.lambda$init$2(TabContainerWidget.java:190)
	at me.shedaniel.rei.impl.client.gui.widget.TabWidget.method_25402(TabWidget.java:86)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25402(DelegateWidgetWithTranslate.java:82)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.method_25402(AbstractDisplayViewingScreen.java:463)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25402(DefaultDisplayViewingScreen.java:500)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	... 18 more
15:09:40.707
craftpresence
CraftPresence
Shutting down CraftPresence...

### Mod pack version

v2.9.0

**Comment by JowMK** [comment]
I saw the version of Farmer's Delight used is Deprecated, maybe it has something to do with it?

**Comment by etendards** [comment]
I can no longer cut items on the cutting board that I could a couple patches ago.

**Comment by KevzCz** [comment]
updating item obliterator will now fix it by the way
